services:
  utils:
    build:
      context: repos/emergency-alerts-utils
      dockerfile: Dockerfile.eas-base
    image: localhost/eas-localenv-base
    command:
      - "echo"
      - "This is utils - just a base image that doesn't do anything."
    restart: "no"

  api:
    build:
      context: repos/emergency-alerts-api
      dockerfile: Dockerfile.eas-api
      args:
        BASE_IMAGE: localhost/eas-localenv-base
    image: localhost/eas-localenv-api
    restart: always
    command:
      - bash
      - -c
      - . /eas/emergency-alerts-api/environment.sh && bash /start-api.sh
    environment:
      SERVICE_ACTION: run_api
      AWS_ENDPOINT_URL_LAMBDA: http://lambda:5000

      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_SERVICE_NAME: api
      OTEL_METRICS_EXPORTER: none
    ports:
      - "6011:6011"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api:/eas/emergency-alerts-api:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-api/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api/scripts/start-api.sh:/start-api.sh:ro,z
    depends_on:
      - pg
      - localstack

  api-worker:
    build:
      context: repos/emergency-alerts-api
      dockerfile: Dockerfile.eas-api
      args:
        BASE_IMAGE: localhost/eas-localenv-base
    image: localhost/eas-localenv-api
    restart: always
    command:
      - bash
      - -c
      - . /eas/emergency-alerts-api/environment.sh && bash /start-api.sh
    environment:
      SERVICE_ACTION: run_worker
      AWS_ENDPOINT_URL_LAMBDA: http://lambda:5000
      WORKER_QUEUE_NAMES: local-dramatiq-periodic-tasks local-dramatiq-broadcast-tasks local-dramatiq-high-priority-tasks

      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_SERVICE_NAME: api-worker
      OTEL_METRICS_EXPORTER: none
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api:/eas/emergency-alerts-api:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-api/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api/scripts/start-api.sh:/start-api.sh:ro,z
    extra_hosts:
      - "api:host-gateway"
    depends_on:
      - pg
      - localstack

  api-periodiq:
    build:
      context: repos/emergency-alerts-api
      dockerfile: Dockerfile.eas-api
      args:
        BASE_IMAGE: localhost/eas-localenv-base
    image: localhost/eas-localenv-api
    restart: always
    command:
      - bash
      - -c
      - . /eas/emergency-alerts-api/environment.sh && bash /start-api.sh
    environment:
      SERVICE_ACTION: run_periodiq

      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_SERVICE_NAME: api-periodiq
      OTEL_METRICS_EXPORTER: none
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api:/eas/emergency-alerts-api:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-api/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api/scripts/start-api.sh:/start-api.sh:ro,z
    extra_hosts:
      - "api:host-gateway"
    depends_on:
      - pg
      - localstack

  api-dlq-watcher:
    build:
      context: repos/emergency-alerts-api
      dockerfile: Dockerfile.eas-api
      args:
        BASE_IMAGE: localhost/eas-localenv-base
    image: localhost/eas-localenv-api
    restart: always
    command:
      - bash
      - -c
      - . /eas/emergency-alerts-api/environment.sh && bash /start-api.sh
    environment:
      SERVICE_ACTION: run_dlq_watcher

      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_SERVICE_NAME: api-dlq-watcher
      OTEL_METRICS_EXPORTER: none
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api:/eas/emergency-alerts-api:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-api/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api/scripts/start-api.sh:/start-api.sh:ro,z
    extra_hosts:
      - "api:host-gateway"
    depends_on:
      - pg
      - localstack

  admin:
    build:
      context: repos/emergency-alerts-admin
      dockerfile: Dockerfile.eas-admin
      args:
        BASE_IMAGE: localhost/eas-localenv-base
    image: localhost/eas-localenv-admin
    restart: always
    command:
      - bash
      - -c
      - . /eas/emergency-alerts-admin/environment.sh && bash /start.sh
    ports:
      - "6012:6012"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-admin:/eas/emergency-alerts-admin:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-admin/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-admin/scripts/start.sh:/start.sh:ro,z
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_SERVICE_NAME: admin
      OTEL_METRICS_EXPORTER: none
    extra_hosts:
      - "api:host-gateway"
    depends_on:
      - localstack

  govuk:
    build:
      context: repos/emergency-alerts-govuk
      dockerfile: Dockerfile.eas-govuk-alerts
      args:
        BASE_IMAGE: localhost/eas-localenv-base
    image: localhost/eas-localenv-govuk
    restart: always
    command:
      - bash
      - -c
      # GovUK doesn't have an application.py file... So we need Flask to import the 'app' module instead:
      - . /eas/emergency-alerts-govuk/environment.sh && export FLASK_APP=app && bash /start-govuk.sh
    ports:
      - "6017:6017"
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: always_on
      OTEL_SERVICE_NAME: govuk-alerts
      OTEL_METRICS_EXPORTER: none
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-govuk:/eas/emergency-alerts-govuk:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-govuk/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-govuk/scripts/start-govuk.sh:/start-govuk.sh:ro,z
    extra_hosts:
      - "api:host-gateway"
    depends_on:
      - localstack

  db-init:
    image: localhost/eas-localenv-api
    user: root # Override so we can install packages
    restart: "no"
    entrypoint: /eas/db-init.sh
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-api:/eas/emergency-alerts-api:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-utils:/eas/emergency-alerts-utils:z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/repos/emergency-alerts-tooling:/eas/emergency-alerts-tooling:z

      - ${LOCAL_WORKSPACE_FOLDER:-.}/environment.sh:/eas/emergency-alerts-api/environment.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/db-init.sh:/eas/db-init.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/gen-api-key-secret.py:/eas/gen-api-key-secret.py:ro,z
    depends_on:
      - pg

  pg:
    image: postgis/postgis:14-3.5
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # As a cheat way of having a dummy CBC we just mock the Lambda API itself
  # with a hardcoded response
  lambda:
    image: python:3.12-alpine
    restart: always
    command:
      - "python"
      - "/lambda-api.py"
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/lambda-api.py:/lambda-api.py:ro,z

  localstack:
    image: localstack/localstack:4.11.1
    restart: always
    ports:
      - "4566:4566"
      # - "4571:4571"
    environment:
      - SERVICES=s3,sqs,cloudwatch,ssm,ses
      - DEBUG=1
      - LOCALSTACK_HOST=localstack
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/localstack.sh:/etc/localstack/init/ready.d/localstack.sh:ro,z
      - ${LOCAL_WORKSPACE_FOLDER:-.}/area-data:/area-data:ro,z

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.15.1
    restart: always
    environment:
      - LOG_LEVEL=debug
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

volumes:
  pg-data: {}
